name: indecision_machine
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.3.2 # Persistence
  uuid: ^4.5.0
  intl: ^0.19.0
  provider: ^6.1.2
  flutter_iconpicker: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
